INSERT INTO movies (movie_name, genre, year, createdAt, updatedAt) VALUES ('The Shawshank Redemption', 'Drama', "2014", CURDATE(), CURDATE());
INSERT INTO movies (movie_name, genre, year, createdAt, updatedAt) VALUES ('The Godfather', 'Drama, Action', "1972", CURDATE(), CURDATE());
INSERT INTO movies (movie_name, genre, year, createdAt, updatedAt) VALUES ('The Godfather Pt.2', 'Drama, Action', "1974", CURDATE(), CURDATE());
INSERT INTO movies (movie_name, genre, year, createdAt, updatedAt) VALUES ('The Dark Knight', 'Drama, Action, Crime', "2008", CURDATE(), CURDATE());
INSERT INTO movies (movie_name, genre, year, createdAt, updatedAt) VALUES ('12 Angry Men', 'Drama', "1957", CURDATE(), CURDATE());
INSERT INTO movies (movie_name, genre, year, createdAt, updatedAt) VALUES ("Schindler's List", 'Drama', "1993", CURDATE(), CURDATE());
INSERT INTO movies (movie_name, genre, year, createdAt, updatedAt) VALUES ('The Lord of the Rings: The Return of the King', 'Drama, Adventure, Fantasy', "2003", CURDATE(), CURDATE());
INSERT INTO movies (movie_name, genre, year, createdAt, updatedAt) VALUES ('Pulp Fiction', 'Drama, Crime', "1994", CURDATE(), CURDATE());
INSERT INTO movies (movie_name, genre, year, createdAt, updatedAt) VALUES ('The Good, The Bad, and The Ugly', 'Western', "1966", CURDATE(), CURDATE());
INSERT INTO movies (movie_name, genre, year, createdAt, updatedAt) VALUES ('Fight Club', 'Drama', "1999", CURDATE(), CURDATE());